FROM golang:1.24-alpine AS builder
ARG BINARY_PATH
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /main ${BINARY_PATH}
FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/
COPY --from=builder /main .
ARG CONFIG_PATH
COPY ${CONFIG_PATH} ./config.yml
CMD ["./main"]